course_name = "电磁场"
course_code = "EE2003"
repo_type = "normal"

[lecturers]

[[lecturers.items]]
name = "张弦"

[[lecturers.items.reviews]]
content = """
授课风格：活力满满，超级讲课人
听课建议：在前期速度较慢的时候边做笔记时注意理解相关推导，后期速度起飞时课后及时整理上课内容。
"""

[[sections]]
title = "教材"

[[sections.items]]
content = """
- **工程电磁场导论**（冯慈璋 / 马西奎 / 高等教育出版社 / 第四版 / textbook）
    - 主教材为这一本，老师的符号也与本书一致，但是后期会跳过部分内容，如需按照课本学习，可以参考老师的预习 PPT 进行取舍。
- **电动力学导论**（David.J.Griffiths / 第三版 / textbook）
    - 此书为电磁场很经典一本教材，但是符号与国内颇有不同。
"""
[[sections]]
title = "关于考试"

[[sections.items]]
content = "考试题目大多出自PPT例题、作业题、MOOC 测试题，有许多概念性辨析的题目，注意理解相关概念，平时熟练掌握的话并不难以完成。"
author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-06" }

[[sections]]
title = "关于实验"

[[sections.items]]
content = "实验共两个，分别是使用 MatLab 进行 DFM 仿真和使用 FEMM 软件进行 DEM 仿真。这两种方法是电磁场数值分析的两种重要方法。初上手可能会被卡住，指导书看不懂时多像老师提问。"
author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-06" }

[[sections]]
title = "学习建议"

[[sections.items]]
content = """
第零章是矢量分析，作为全书的数学基础。第一章由熟悉的静电场分析为全书打下分析方法基础，接着恒定电场、恒定磁场，再到时变电磁场和准静态电磁场，后续的分析思路都与第一章类似。

由于学时不够，因此第一章结束后速度会越来越快，注意各场之间的类比和区别对比，运用**类比**和**对比**的方法进行学习。
"""
author = { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-06" }

[[sections.items]]
content = """
老师讲的很好，备考时主要复习 PPT，作业题目和 MOOC 题目。

MOOC 尽量少丢分，不划算。
"""
author = { name = "SSC", link = "https://github.com/SSC202", date = "2024-12" }

